// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RELEX.InventoryManager.SqlData.Contexts;

#nullable disable

namespace RELEX.InventoryManager.SqlData.Migrations
{
    [DbContext(typeof(InventoryContext))]
    [Migration("20251217145152_SeedOrderMigrations")]
    partial class SeedOrderMigrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("inv")
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RELEX.InventoryManager.SqlData.Entities.OrderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("LocationCode")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateOnly>("OrderDate")
                        .HasColumnType("date");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SubmittedBy")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "LocationCode" }, "IX_Order_LocationCode");

                    b.HasIndex(new[] { "OrderDate" }, "IX_Order_OrderDate");

                    b.HasIndex(new[] { "ProductCode" }, "IX_Order_ProductCode");

                    b.ToTable("Orders", "inv");
                });
#pragma warning restore 612, 618
        }
    }
}
